name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  OPENVPNAS_VERSION: 2.13.1-d8cdeb9c-Debian12
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg="OPENVPNAS_VERSION=${OPENVPNAS_VERSION}" --tag openvpnas:latest
